export default {
  // BASE_URL: Config.API_URL,
  BASE_URL: "http://localhost:5166",
  HOME: "/WeatherForecast",
  USER_REGISTER: "api/User/create",
  USER_LOGIN: "/api/User/login",
  WORKOUT_PLAN: "/api/WorkoutPlan",
  WORKOUT_PLAN_ENROLL: "api/UserWorkoutEnrollment/single",
  WORKOUT: "/api/Workout",
  USER_ENROLLED_WORKOUT_PLAN: "/api/UserWorkoutEnrollment/user",
  COMPLETE_WORKOUT: "api/UserWorkoutEnrollment/complete",
  WEIGHT: "/api/User/Wieght",
  CHEAT_MEAL: "/api/CheatMeal",
  REPORT: "/api/User/Report",
};
