export const WORKOUT_PLAN_ENROLL_REQUEST = "WORKOUT_PLAN_ENROLL_REQUEST";
export const WORKOUT_PLAN_ENROLL_SUCCESS = "WORKOUT_PLAN_ENROLL_SUCCESS";
export const WORKOUT_PLAN_ENROLL_FAILED = "WORKOUT_PLAN_ENROLL_FAILED";

export const GET_WORKOUT_PLAN_LIST_REQUEST = "GET_WORKOUT_PLAN_LIST_REQUEST";
export const GET_WORKOUT_PLAN_LIST_SUCCESS = "GET_WORKOUT_PLAN_LIST_SUCCESS";
export const GET_WORKOUT_PLAN_LIST_FAILED = "GET_WORKOUT_PLAN_LIST_FAILED";

export const GET_WORKOUT_PLAN_DETAILS_REQUEST =
  "GET_WORKOUT_PLAN_DETAILS_REQUEST";
export const GET_WORKOUT_PLAN_DETAILS_SUCCESS =
  "GET_WORKOUT_PLAN_DETAILS_SUCCESS";
export const GET_WORKOUT_PLAN_DETAILS_FAILED =
  "GET_WORKOUT_PLAN_DETAILS_FAILED";

export const SUBMIT_COMPLETED_WORKOUT_REQUEST =
  "SUBMIT_COMPLETED_WORKOUT_REQUEST";
export const SUBMIT_COMPLETED_WORKOUT_SUCCESS =
  "SUBMIT_COMPLETED_WORKOUT_SUCCESS";
export const SUBMIT_COMPLETED_WORKOUT_FAILED =
  "SUBMIT_COMPLETED_WORKOUT_FAILED";

export const GET_USER_ENROLLED_WORKOUT_PLAN_REQUEST =
  "GET_USER_ENROLLED_WORKOUT_PLAN_REQUEST";
export const GET_USER_ENROLLED_WORKOUT_PLAN_SUCCESS =
  "GET_USER_ENROLLED_WORKOUT_PLAN_SUCCESS";
export const GET_USER_ENROLLED_WORKOUT_PLAN_FAILED =
  "GET_USER_ENROLLED_WORKOUT_PLAN_FAILED";
