export const TEST_ACTION = "TEST_ACTION";
export const TEST_ACTION_SUCCESS = "TEST_ACTION_SUCCESS";
export const TEST_ACTION_FAILED = "TEST_ACTION_FAILED";

export const WORKOUT_PLAN_ENROLL_REQUEST = "WORKOUT_PLAN_ENROLL_REQUEST";
export const WORKOUT_PLAN_ENROLL_SUCCESS = "WORKOUT_PLAN_ENROLL_SUCCESS";
export const WORKOUT_PLAN_ENROLL_FAILED = "WORKOUT_PLAN_ENROLL_FAILED";
